FROM node:18.16
RUN mkdir /usr/src/fabulous
WORKDIR /usr/src/fabulous
COPY package*.json /usr/src/fabulous
RUN npm install
COPY . /usr/src/fabulous

ENV TOKEN=
ENV clientId=

CMD ["npm", "run", "start"]